<?php
/**
 * Return the default options of the theme
 * 
 * @return  void
 */

function themesflat_customize_default($key) {
	$default = array(
		'social_links'	=> array ("facebook" => '#', "twitter" => '#', "instagram" => '#', "linkedin"  => '#'),
		'show_social_share' => 0,		
		'social_footer' => 0,
		'go_top' => 1,
		'btn_darkmode' => 1,
		'message_background_color'	=> '',
		'message_textcolor'	=> '',
		'message_link_color' => '',
		'message_link_color_hover' => '',
		'header_message' => 0 ,
		'social_header' => 1,
		'logo_controls' => array('padding-top' => '','padding-bottom' => ''),
		'style_header'	=> 'header-default',	
		'header_backgroundcolor'=>'#ffffff',
		'header_background_bottom_color'=>'',
		'header_sticky' => 1,
		'header_content_right' => '',
		'header_absolute'	=> 0,		
		'header_time'	=> 0,	

		'style_background' => 'none',
		'video_background' => 'video-1',


		'show_post_navigator' => 0,
		'show_entry_footer_content'	=> 0,
		'logo_width' => 60,
		'menu_location_primary' => 'primary',
		'site_logo'	=> THEMESFLAT_LINK . 'images/logo.png',
		'site_logo_white'	=> THEMESFLAT_LINK . 'images/logo.png',
		'site_logo_sticky'	=> THEMESFLAT_LINK . 'images/logo.png',
		'site_logo_fixed'	=> THEMESFLAT_LINK . 'images/logo.png',
		'site_logo_mobile'	=> THEMESFLAT_LINK . 'images/logo.png',	
		'header_color_sticky' => '',
		'show_bottom' => 1,		
		'header_backgroundcolor_sticky'=>'#fff',	

		'primary_color'=>'#0C171A',
		'secondary_color'=>'#FF3F25',
		'accent_color'=>'#0B55E5',
		
		'typography_body' => array(
			'family' => 'Apfel Grotezk',
			'style'  => '400',
			'size'   => '16',
			'line_height'=>'26px',
			'letter_spacing' => '0px',
		),
		'body_text_color'=>'#666B68',
		'body_background_color' => '',
		'page_sidebar_layout' => 'sidebar-right',
		'content_controls' => array('padding-top' => 130,'padding-bottom' => 130),

		'typography_menu' => array(
			'family' => 'Apfel Grotezk',
			'style'  => '500',
			'size'   => '18',
			'line_height'=>'70px',
			'letter_spacing' => '0px',
		), 
		'mainnav_color'		=> '#0C171A',
		'mainnav_hover_color'=>'#FF3F25',
		'mainnav_active_color'=>'#FF3F25',
		'sub_sub_nav_color'=>' #0C171A',
		'sub_sub_nav_background'=>'#FFFFFF',
		'sub_sub_nav_color_hover'=>'#FF3F25',
		'sub_sub_nav_background_hover'=>'',
		'menu_distance_between' => 20,
		'typography_sub_menu' => array(
			'family' => 'Apfel Grotezk',
			'style'  => '500',
			'size'   => '16',
			'line_height'=>'24px',
			'letter_spacing' => '0px',
		),
		'sub_nav_color'		=>'#0C171A',		
		'sub_nav_color_hover'	=>	'#FF3F25',
		'sub_nav_background'=>'#FFFFFF',
		'sub_nav_background_hover'=>'',
		'sub_nav_border_color' => '',
		'typography_headings'	=> array(
			'family' => 'Apfel Grotezk',
			'style'  => '700',
			'line_height'=>'1.333',
			'letter_spacing' => '0px'		
		),
		'h1_size' => 75,
		'h2_size' => 48,
		'h3_size' => 27,
		'h4_size' => 24,
		'h5_size' => 22,
		'h6_size' => 20,
		'typography_blockquote' => array(
			'family' => 'Apfel Grotezk',
			'style'  => '700',
			'size'   => '24',
			'line_height'=>'32px',
			'letter_spacing' => '0px',
		),	
		'typography_blog_post_title' => array(
			'family' => 'Apfel Grotezk',
			'style'  => '700',
			'size'   => '35',
			'line_height'=>'40px',
			'letter_spacing' => '',
		),
		'typography_blog_post_meta' => array(
			'family' => 'Apfel Grotezk',
			'style'  => '400',
			'size'   => '16',
			'line_height'=>'26px',
			'letter_spacing' => '',
		),
		'typography_blog_post_buttons' => array(
			'family' => 'Apfel Grotezk',
			'style'  => '700',
			'size'   => '14',
			'line_height'=>'22px',
			'letter_spacing' => '0px',
		),
		'typography_blog_single_title' => array(
			'family' => 'Apfel Grotezk',
			'style'  => '700',
			'size'   => '48',
			'line_height'=>'55px',
			'letter_spacing' => '',
		),
		'typography_blog_single_comment_title' => array(
			'family' => 'Apfel Grotezk',
			'style'  => '500',
			'size'   => '32',
			'line_height'=>'40px',
			'letter_spacing' => '0px',
		),
		'typography_sidebar_widget_title' => array(
			'family' => 'Apfel Grotezk',
			'style'  => '700',
			'size'   => '22',
			'line_height'=>'28px',
			'letter_spacing' => '0px',
		),	
		'typography_footer_widget_title' => array(
			'family' => 'Apfel Grotezk',
			'style'  => '600',
			'size'   => '22',
			'line_height'=>'20px',
			'letter_spacing' => '',
		),	
		'typography_page_title'	=> array(
			'family' => 'Apfel Grotezk',
			'style'  => '700',
			'size'   => '75',
			'line_height'=>'80px',
			'letter_spacing' => '',
		),
		'page_title_text_color' => '',		
		'page_title_controls' => array('padding-top' => 100, 'padding-bottom' => 100),
		'page_title_image_size' => 'cover',
		'page_title_heading_enabled' => 1,
		'typography_breadcrumb'	=> array(
			'family' => 'Apfel Grotezk',
			'style'  => '600',
			'size'   => '27',
			'line_height'=>'1.5',
			'letter_spacing' => '0px',
		),
		'bread_crumb_prefix' =>'',
		'bread_crumb_description' =>'',
		'breadcrumb_separator' =>  '/',
		'breadcrumb_color' => '#FFFFFF',

		'typography_buttons' => array(
			'family' => 'Apfel Grotezk',
			'style'  => '700',
			'size'   => '14',
			'line_height'=>'22px',
			'letter_spacing' => '0px',
		),
		'typography_pagination'	=> array(
			'family' => 'Apfel Grotezk',
			'style'  => '600',
			'size'   => '18',
			'line_height'=>'24px',
			'letter_spacing' => '0px',
		),		
		'typography_bottom_menu' => array(
			'family' => 'Apfel Grotezk',
			'style'  => '400',
			'size'   => '16',
			'line_height'=>'24px',
			'letter_spacing' => '0px',
		),
		'breadcrumb_enabled' => 1,
		'show_post_paginator' => 1,
		'post_content_elements' => 'meta,title,readmore',
		'blog_archive_exclude' => '',
		'blog_featured_title' => 'Blog Details',
		'sidebar_layout' => 'sidebar-right',
		'related_post_style'	=> 'blog-grid',
		'grid_columns_post_related' => 2,
		'number_related_post' => 2,
		'blog_sidebar_list'		  => 'blog-sidebar',	
		'blog_archive_readmore' => 1,
		'blog_archive_post_excepts_length' => 25,
		'blog_archive_readmore_text' => 'Read more <i class="icon-isak-arrow-right"></i>',
		'blog_archive_pagination_style' => 'pager-numeric',
		'blog_posts_per_page'	=> 3,
		'blog_order_by'	=> 'date',
		'blog_order_direction' => 'DESC',
		'page_sidebar_list'	=> 'blog-sidebar',	

		
		'typography_footer' => array(
			'family' => 'Apfel Grotezk',
			'style'  => '400',
			'size'   => '16',
			'line_height'=>'24px',
			'letter_spacing' => '',
		),
		'footer_signature_1'	=> THEMESFLAT_LINK . 'images/signature1.svg',
		'footer_signature_2'	=> THEMESFLAT_LINK . 'images/signature2.svg',
		'footer_background_color'	=> '#0C171A',
		'footer_title_widget_color' => '#fff',
		'footer_text_color'			=> '#A2A3AB',
		'footer_text_color_hover'   => '#317C6F',
		'footer_widget_areas' => 2,
		'footer_controls' => array('padding-top' => '100', 'padding-bottom' =>'' ),
		'footer1' => 'footer-1',
		'footer2' => 'footer-2',
		'footer3' => 'footer-3',
		'footer4' => 'footer-4',
		'footer_background_image' => '',
		'enable_footer_fixed' => 0,
		'footer_image_size' => 'cover',
		'typography_bottom_copyright' => array(
			'family' => 'Apfel Grotezk',
			'style'  => '400',
			'size'   => '16',
			'line_height'=>'22px',
			'letter_spacing' => '',
		),
	
		'bottom_background_color'	=> '#0C171A',
		'bottom_text_color'			=> '#A2A3AB',
		'bottom_link_color'         => '#ffffff',
		'bottom_text_color_hover'   => '',		
		'social_bottom'   => 0,		
		'layout_version'			=> 'wide',		
		'footer_copyright'			=> '©<a href="https://themeforest.net/user/themesflat/portfolio">Themesflat </a>, All rights reserved',
		'footer_cover_letter'			=> '<span class="text-black-56">“</span>
                                        Design is not just what it looks like and feels like. Design is how it works.
                                        <span class="text-black-56">“</span>',
		'footer_cover_letter_author'			=> 'Steve Jobs',
		'enable_smooth_scroll'	=> 0,
		'enable_preload' => 1,
		'preload' => 'preload-6',
		'page_title_alignment' => 'center',

		'white_color'         => '#ffffff',
		'black_color'         => '#000000',
		'primary_color'         => '#00DE51',
		'surface_color'         => '#F5F5F5',

	);
	return $default[$key];
}